name: Test

on: 
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main 
      - devel

jobs: 
  test:
    name: Test
    runs-on: ubuntu-latest 

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Creating .env
        run: |
          cat <<EOF > .env
          POSTGRES_HOST=db
          POSTGRES_DB=postgres
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=password
          EOF

      - name: Run docker compose
        run: docker compose up -d --build

      - name: Wait building
        run: sleep 5

      - name: Test
        run: docker compose exec web pytest

      - name: Closing containers
        if: always()
        run: docker compose down
